Phase 1 of numpy basic (importent only)
 
 1- array
 2- arange
 3- zeros
 4- ones
 5- linspace
 6- reshape
 7- resize
 8- sum()
 9- np.sum(asix=)
 

In [46]:
import numpy as np
arr =  np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
l =  [[1,2,3,],[4,5,6,],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr= np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [17]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:

arr = np.linspace(1, 5, 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
#array concadination
a = np.array([1,2])
b = np.array([3,4])

print(a+b)

[4 6]


In [45]:
#reshaping in nympay use .reshap( method)
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)


[[1 2 3]
 [4 5 6]]


In [28]:
arr = np.array([10,20,30])

print(arr + 2)

[12 22 32]


In [44]:
#Find column-wise sum: ___ .Sum METHOD
arr= np.array([
 [1,2,5],
 [3,4,9]
])

In [42]:
arr.sum()

np.int64(24)

In [43]:
#sum on axis ex 0axix .1axis
np.sum(arr,axis = 0)

array([ 4,  6, 14])

phase2
1- indexing
2-slicing
3-

In [53]:
#to genrate a number form 1-31 as like in python for loop range function
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
#indexing to get 5 element (remember indexting start form 0)
arr[5]

np.int64(6)

In [60]:
#slicing form 5 to 15
arr[5:15]
#slicing form start to 15
arr[:15]
#slicing form one  to end and skip by 2 or as you given the value
arr[1::2]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [65]:
#nympy matrix indexing---
arr = np.arange(1,31).reshape(6,5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
arr[0]

array([1, 2, 3, 4, 5])

In [67]:
arr[5]

array([26, 27, 28, 29, 30])

nympy matrix indexing--- explan

array([[ 1,  2,  3,  4,  5],---index 0
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])----- index5
if you want tartget any single value give you have do like arr[1(raw),1(colum)]output will be 7
what id we want mutlipue balue from differrt commlum do this arr[1(form):3(to in raws),2(from):5(to in rwas)] out put will be[8,9,10
13,14,15]]
    

In [68]:
arr[1,1]

np.int64(7)

In [69]:
arr[1:3,2:5]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [70]:
arr[:,3]#to slic out the collum form all raws

array([ 4,  9, 14, 19, 24, 29])

In [79]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [80]:
bool_index =  arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [81]:
arr = arr[bool_index]#for using this you can get ture value into the numbers
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])