In [8]:
#Broadcasting
import numpy as np
arr= np.array([1,2,3,4])
print(arr+5) #(NumPy internally did:[1,2,3] + [5,5,5])



[6 7 8 9]


In [12]:
#arry optation aithmatic opration
a1= np.array([1,2,3,4,5,6])
a2= np.array([9,8,7,6,5,4])
a1

array([9, 8, 7, 6, 5, 4])

In [13]:
a2

array([9, 8, 7, 6, 5, 4])

In [14]:
a1+a2

array([10, 10, 10, 10, 10, 10])

In [15]:
a1-a2

array([-8, -6, -4, -2,  0,  2])

In [16]:
a1*a2

array([ 9, 16, 21, 24, 25, 24])

In [23]:
#Boolean Masking - Filtering
marks = np.array([10,20,30,40,50,60,70,80,90,])
marks>50
marks [marks>50]

array([60, 70, 80, 90])

In [24]:
arr = np.array([10,20,30,40])

print(arr[arr > 20])

[30 40]


In [34]:
arr= np.array([1,2,3,4])
new_arr = arr.copy()
new_arr[0]=10
arr
new_arr


array([1, 2, 3, 4])

In [35]:
new_arr[0]=10

In [36]:
new_arr

array([10,  2,  3,  4])

In [37]:
arr

array([1, 2, 3, 4])

In [38]:
arr = np.array([10,20,30,40,50])

print(arr[::-1])

[50 40 30 20 10]


In [42]:
arr=np.array([
 [1,2,3],
 [4,5,6]
])

arr[::,2]

array([3, 6])

In [47]:
#stack,concadition,
a = np.array([1,2,3])

b = np.array([4,5,6])

In [48]:
a

array([1, 2, 3])

In [49]:
b

array([4, 5, 6])

In [52]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [55]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
arr= np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [62]:
np.vsplit(arr,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]